# This is a basic workflow to help you get started with Actions

name: IDA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      IDA_URL:
        description: 'IDA_URL'
        default: 'https://ida-demo1.fyre.ibm.com:9443/ida'
        required: true
        type: string
      IDA_USERNAME:
        description: 'IDA_USERNAME'
        default: 'idaAdmin'
        required: true
        type: string
      IDA_PASSWORD:
        description: 'IDA_PASSWORD'
        default: 'idaAdmin'
        required: true
        type: string
      PIPELINE_ID:
        description: 'PIPELINE_ID'
        default: '306'
        required: false
        type: string
      PIPELINE_NAME:
        description: 'PIPELINE_NAME'
        default: ''
        required: false
        type: string
      PIPELINE_DATA:
        description: 'PIPELINE_DATA'
        default: ''
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Trigger IDA Pipeline."
          chmod +x *.sh
          ./pipeline.sh -s ${{inputs.IDA_URL}} -u ${{inputs.IDA_USERNAME}} -p ${{inputs.IDA_PASSWORD}} -i ${{inputs.PIPELINE_ID}} -n ${{inputs.PIPELINE_NAME}} -d ${{inputs.PIPELINE_DATA}} -o pipeline
